version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app:ro
      - /app/node_modules
      - /app/attachments
    environment: 
      - NODE_ENV=development
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_IP
      - MONGO_PORT
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
